version: "3.8"
services:
 app:
  build: .
  volumes:
   - .:/djapp
  ports:
   - 8000:8000
  image: app:django 
  container_name: django_app_container
  command: python manage.py runserver 0.0.0.0:8000